# Generated by Django 2.2.2 on 2019-12-30 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('location', models.TextField(blank=True, verbose_name='location')),
                ('container_type', models.CharField(choices=[('BX', 'box'), ('SL', 'shelf'), ('DR', 'drawer'), ('RM', 'room'), ('SR', 'surface'), ('WL', 'wall'), ('OT', 'other')], default='BX', max_length=2)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container')),
            ],
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container')),
                ('tags', models.ManyToManyField(to='inventory.ItemTag')),
            ],
        ),
    ]
