# Generated by Django 2.2.2 on 2020-01-09 17:32

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='container/')),
                ('location_metadata', jsonfield.fields.JSONField(blank=True, default={})),
                ('container_type', models.IntegerField(choices=[(0, 'default'), (1, 'grid'), (2, 'freeform')], default=0)),
                ('metadata', jsonfield.fields.JSONField(default={})),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='container/')),
                ('location_metadata', jsonfield.fields.JSONField(blank=True, default={})),
                ('quantity', models.IntegerField(default=0, verbose_name='quantity')),
                ('alert_quantity', models.IntegerField(default=0, verbose_name='alert quantity')),
                ('source', models.CharField(blank=True, default='', max_length=200, verbose_name='source')),
                ('source_url', models.URLField(blank=True, null=True, verbose_name='source URL')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container')),
                ('tags', models.ManyToManyField(to='inventory.ItemTag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
