# Generated by Django 2.2.2 on 2019-12-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='alert_quantity',
            field=models.IntegerField(default=0, verbose_name='alert quantity'),
        ),
    ]
