# Generated by Django 2.2.2 on 2020-01-03 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='container',
        ),
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(null=True, upload_to='container/'),
        ),
        migrations.AddField(
            model_name='item',
            name='alert_quantity',
            field=models.IntegerField(default=0, verbose_name='alert quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='item/'),
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container', verbose_name='container'),
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='source URL'),
        ),
    ]
