# Generated by Django 2.2.2 on 2020-01-09 18:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_itemattributenum_itemattributestr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_reusable', models.BooleanField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='alert_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='alert quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('used_items', models.ManyToManyField(through='inventory.ItemUsage', to='inventory.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemusage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Item'),
        ),
        migrations.AddField(
            model_name='itemusage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Project'),
        ),
    ]
