# Generated by Django 2.2.2 on 2019-12-30 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_alert_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='container',
        ),
        migrations.AddField(
            model_name='item',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Container', verbose_name='container'),
        ),
    ]
