# Generated by Django 2.2.2 on 2020-01-06 01:01

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200105_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='container_metadata',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='item',
            name='container_metadata',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
