# Generated by Django 2.2.2 on 2020-01-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20200109_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='container/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='container/'),
        ),
    ]
