# Generated by Django 2.2.2 on 2019-12-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191230_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='source'),
        ),
        migrations.AddField(
            model_name='item',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='source URL'),
        ),
    ]
