# Generated by Django 2.2.2 on 2020-01-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20191230_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='image',
            field=models.ImageField(null=True, upload_to='container/images'),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='container/images'),
        ),
    ]
