# Generated by Django 2.2.2 on 2020-01-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200105_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container_metadata',
            new_name='location_metadata',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='container_metadata',
            new_name='location_metadata',
        ),
        migrations.RemoveField(
            model_name='container',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'grid'), (2, 'freeform')]),
        ),
    ]
