# Generated by Django 2.2.2 on 2020-01-12 00:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20200111_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alert_quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='alert quantity'),
        ),
    ]
