# Generated by Django 2.2.2 on 2020-01-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200111_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, to='inventory.ItemTag'),
        ),
    ]
