# Generated by Django 2.2.2 on 2020-01-06 05:25

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200105_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='metadata',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
