# Generated by Django 2.2.2 on 2020-01-02 01:08

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20200101_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemtag',
            name='image',
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='item/', validators=[inventory.models.validate_image]),
        ),
    ]
