# Generated by Django 2.2.2 on 2020-01-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_container_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_type',
            field=models.IntegerField(choices=[(0, 'default'), (1, 'grid'), (2, 'freeform')], default=0),
        ),
    ]
