# Generated by Django 3.0.6 on 2020-05-24 21:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20200115_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUUID',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid1, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Container')),
            ],
        ),
        migrations.CreateModel(
            name='ContainerUUID',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid1, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Container')),
            ],
        ),
    ]
